spring:
  datasource: # 数据库链接
    #本地服务器连接
    url: jdbc:mysql://10.51.13.130:6006/bi_scheduler?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: zhwyonly
    password: Fmc123456
    #华为云服务器连接
#    url: jdbc:mysql://124.71.98.1:6006/bi_scheduler?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: ifm
#    password: Ifm@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 18000000
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    show-sql: true # sql打印
    database-platform: org.hibernate.dialect.MySQLDialect # 数据库方言
    open-in-view: false # false关闭懒加载
logging: # 日志记录
  level:
    root: info
    org.kettle.scheduler: info
  file: /logs/${spring.application.name}.log
